# **Sequence Perplexity**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# algorithms4pepprotgraphs framework
sys.path.append('/home/jovyan/work/algorithms4pepprotgraphs')
from algorithms4pepprotgraphs.module.notebook import NotebookApp
from algorithms4pepprotgraphs.util.plotting import histogram

app = NotebookApp('.env.jupyter.StarPep')
paths = app.paths()

[2025-04-07 20:04:35,159] WARNING [data_validator.py:87] Sequences with non-natural amino acids were excluded. See: /home/jovyan/work/output/results/StarPep/Log/Sequences with Non-Natural Amino Acids.csv
[2025-04-07 20:04:47,846] INFO [notebook.py:70] Setting:
dataset_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/StarPep/StarPep.csv
pdb_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/StarPep/ESMFold_pdbs
notebook_output_path: /home/jovyan/work/output/results/StarPep
sequence_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/results/StarPep/2025-04-07T19.42.20-Sequence_Analyzer
graph_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/results/StarPep/2025-04-07T19.56.31-Graph_Analyzer
min_seq_len: 10
max_seq_len: 100

## 📊 **Data Analysis**

### **Sequence Length Data**

In [2]:
data = pd.read_csv(app.sequence_analysis['sequence_length'])
data.head()

                                sequence  length
0             GIGAVLKVLTTGLPALISWIKRKRQQ      26
1                GIGKFLHSAKKFGKAFVGEIMNS      23
2                          ILPWKWPWWPWRR      13
3                      KWCFRVCYRGICYRRCR      17
4  LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES      37

### **Analysis by Interval Length**

In [3]:
intervals = {
    '0-5': (0, 5),
    '0-10': (0, 9),
    '10-30': (10, 30),
    '10-50': (10, 50),
    '10-100': (10, 100),
    '>100': (100.1, float('inf'))
}

summary = {key: ((data['length'] >= val[0]) & (data['length'] <= val[1])).sum() for key, val in intervals.items()}

summary_df = pd.DataFrame.from_dict(summary, orient='index', columns=['Count'])
summary_df

        Count
0-5         0
0-10        0
10-30   21272
10-50   28069
10-100  34636
>100        0

### **Statistical Analysis**

In [4]:
data['length'].describe()

count    34636.000000
mean        32.169766
std         21.923882
min         10.000000
25%         15.000000
50%         24.000000
75%         42.000000
max        100.000000
Name: length, dtype: float64