# **Sequence Perplexity**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# PepProtGraphAnalyzer framework
sys.path.append('/home/jovyan/work/PepProtGraphAnalyzer')
from PepProtGraphAnalyzer.module.notebook import NotebookApp
from PepProtGraphAnalyzer.util.plotting import histogram

app = NotebookApp('.env.jupyter.StarPep')
paths = app.paths()

[2025-09-23 19:42:03,359] WARNING [data_validator.py:87] Sequences with non-natural amino acids were excluded. See: /home/jovyan/work/output/out_paper/Starpep/Log/Sequences with Non-Natural Amino Acids.csv
[2025-09-23 19:42:10,478] INFO [notebook.py:70] Setting:
dataset_path: /home/jovyan/work/PepProtGraphAnalyzer/dataset/StarPep/StarPep.csv
pdb_path: /home/jovyan/work/PepProtGraphAnalyzer/dataset/StarPep/ESMFold_pdbs
notebook_output_path: /home/jovyan/work/output/out_paper/Starpep
sequence_analysis_path: /home/jovyan/work/PepProtGraphAnalyzer/output/results_with_seq_10_to_100/StarPep/2025-04-07T19.42.20-Sequence_Analyzer
graph_analysis_path: /home/jovyan/work/PepProtGraphAnalyzer/output/results_with_seq_10_to_100/StarPep/2025-04-07T19.56.31-Graph_Analyzer
min_seq_len: 10
max_seq_len: 100

## 📊 **Data Analysis**

### **Sequence Length Data**

In [2]:
data = pd.read_csv(app.sequence_analysis['sequence_length'])
data.head()

                                sequence  length
0             GIGAVLKVLTTGLPALISWIKRKRQQ      26
1                GIGKFLHSAKKFGKAFVGEIMNS      23
2                          ILPWKWPWWPWRR      13
3                      KWCFRVCYRGICYRRCR      17
4  LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES      37

### **Analysis by Interval Length**

In [3]:
intervals = {
    '[1-10)': (1, 9),
    '[10-20)': (10, 19),
    '[20-30)': (20, 29),
    '[30-40)': (30, 39),
    '[40-50)': (40, 49),
    '[50-60)': (50, 59),
    '[60-70)': (60, 69),
    '[70-80)': (70, 79),
    '[80-90)': (80, 89),
    '[90-100]': (90, 100),
    '>100': (101, float('inf'))
}

summary = {key: ((data['length'] >= val[0]) & (data['length'] <= val[1])).sum() for key, val in intervals.items()}

output = paths['sequence_length_path'].joinpath("Sequence Length Summary.csv")

summary_df = pd.DataFrame.from_dict(summary, orient='index', columns=['Count'])
summary_df.to_csv(output)
summary_df

          Count
[1-10)        0
[10-20)   12987
[20-30)    7568
[30-40)    4859
[40-50)    2109
[50-60)    1702
[60-70)    2112
[70-80)    1663
[80-90)     862
[90-100]    774
>100          0

### **Statistical Analysis**

In [4]:
data['length'].describe()

count    34636.000000
mean        32.169766
std         21.923882
min         10.000000
25%         15.000000
50%         24.000000
75%         42.000000
max        100.000000
Name: length, dtype: float64