# **Sequence Perplexity**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# algorithms4pepprotgraphs framework
sys.path.append('/home/jovyan/work/algorithms4pepprotgraphs')
from algorithms4pepprotgraphs.module.notebook import NotebookApp
from algorithms4pepprotgraphs.util.plotting import histogram

app = NotebookApp('.env.jupyter.AVPDiscover.All')
paths = app.paths()

[2025-03-31 01:29:35,583] CRITICAL [db_manager.py:372] There are sequences for which data ingestion has not been performed.

Exception: There are sequences for which data ingestion has not been performed.

## 📊 **Data Analysis**

### **Sequence Length Data**

In [36]:
data = pd.read_csv(app.sequence_analysis['sequence_length'])
data.head()

                   sequence  length
0      LQQLLFIAFRIGRRRRRRRR      20
1      LAQLLFIHFRIGRRRRRRRR      20
2  IIRILQQLLFIHFRIGRRRRRRRR      24
3      LQQLLFIHFAIGRRRRRRRR      20
4      LQQLLFIHFRAGRRRRRRRR      20

### **Analysis by Interval Length**

In [35]:
intervals = {
    '0-5': (0, 5),
    '0-10': (0, 10),
    '10-30': (10, 30),
    '10-50': (10, 50),
    '10-100': (10, 100),
    '>100': (100.1, float('inf'))
}

summary = {key: ((data['length'] >= val[0]) & (data['length'] <= val[1])).sum() for key, val in intervals.items()}

summary_df = pd.DataFrame.from_dict(summary, orient='index', columns=['Count'])
summary_df

        Count
0-5        79
0-10     1204
10-30   10045
10-50   15182
10-100  16821
>100        0

### **Statistical Analysis**

In [34]:
data['length'].describe()

count    17889.000000
mean        29.086869
std         17.395412
min          5.000000
25%         17.000000
50%         25.000000
75%         36.000000
max        100.000000
Name: length, dtype: float64