# **Sequence Perplexity**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# algorithms4pepprotgraphs framework
sys.path.append('/home/jovyan/work/algorithms4pepprotgraphs')
from algorithms4pepprotgraphs.module.notebook import NotebookApp
from algorithms4pepprotgraphs.util.plotting import histogram

app = NotebookApp('.env.jupyter.AVPDiscover.Ext')
paths = app.paths()

[2025-04-10 23:42:21,183] WARNING [data_validator.py:87] Sequences with non-natural amino acids were excluded. See: /home/jovyan/work/output/results_with_seq_2_to_100/AVP-external/Log/Sequences with Non-Natural Amino Acids.csv
[2025-04-10 23:42:37,954] INFO [notebook.py:70] Setting:
dataset_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/AVPDiscover/AVP-external.csv
pdb_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/AVPDiscover/ESMFold_pdbs
notebook_output_path: /home/jovyan/work/output/results_with_seq_2_to_100/AVP-external
sequence_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/results_with_seq_2_to_100/AVP-external/2025-04-10T21.53.47-Sequence_Analyzer
graph_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/results_with_seq_2_to_100/AVP-external/2025-04-10T21.59.42-Graph_Analyzer
min_seq_len: None
max_seq_len: 100

## 📊 **Data Analysis**

### **Sequence Length Data**

In [2]:
data = pd.read_csv(app.sequence_analysis['sequence_length'])
data.head()

                                sequence  length
0               FLPLLAGLAANFLPTIICKISYKC      24
1  KWKLFKKIEKVGQNIRDGIIKAGPAVAVVGQATQIAK      37
2     ALWFTMLKKLGTMALHAGKAALGAAANTISQGTQ      34
3                          FVQWFSKFLGRIL      13
4    GFGALFKFLAKKVAKTVAKQAAKQGAKYVVNKQME      35

### **Analysis by Interval Length**

In [3]:
intervals = {
    '[1-10)': (1, 9),
    '[10-20)': (10, 19),
    '[20-30)': (20, 29),
    '[30-40)': (30, 39),
    '[40-50)': (40, 49),
    '[50-60)': (50, 59),
    '[60-70)': (60, 69),
    '[70-80)': (70, 79),
    '[80-90)': (80, 89),
    '[90-100]': (90, 100),
    '>100': (101, float('inf'))
}

summary = {key: ((data['length'] >= val[0]) & (data['length'] <= val[1])).sum() for key, val in intervals.items()}

output = paths['sequence_length_path'].joinpath("Sequence Length Summary.csv")

summary_df = pd.DataFrame.from_dict(summary, orient='index', columns=['Count'])
summary_df.to_csv(output)
summary_df

          Count
[1-10)      521
[10-20)    4230
[20-30)    4917
[30-40)    3285
[40-50)    2789
[50-60)     383
[60-70)     394
[70-80)    1159
[80-90)     929
[90-100]   1668
>100          0

### **Statistical Analysis**

In [4]:
data['length'].describe()

count    20275.000000
mean        39.234032
std         25.862887
min          2.000000
25%         20.000000
50%         30.000000
75%         48.000000
max        100.000000
Name: length, dtype: float64