# Graph Similarity Analysis

In [22]:
import sys
import os
import pandas as pd

In [24]:
filename = 'data/Graph_Analysis/Graph-similari.csv'
graph_information = pd.read_csv(filename)
graphs_similarity.head()

,distance_interval_1,distance_interval_2,average_similarity,minimum_similarity,maximum_similarity
0,"euclidean(0, 10)","euclidean(0, 15)",0.760827,0.162918,0.947292
1,"euclidean(0, 10)","euclidean(0, 20)",0.585839,0.162918,0.907936
2,"euclidean(0, 10)","canberra(0, 0.8)",0.697563,0.502642,0.932950
3,"euclidean(0, 10)","canberra(0, 1.1)",0.692325,0.489952,0.930605
4,"euclidean(0, 10)","canberra(0, 1.4)",0.668923,0.478053,0.937942

In [25]:
graphs_similarity.loc[pd.isna(graphs_similarity['average_similarity'])]

Empty DataFrame
Columns: [distance_interval_1, distance_interval_2, average_similarity, minimum_similarity, maximum_similarity]
Index: []

In [26]:
graphs_similarity.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   distance_interval_1  210 non-null    object
 1   distance_interval_2  210 non-null    object
 2   average_similarity   210 non-null    float64
 3   minimum_similarity   210 non-null    float64
 4   maximum_similarity   210 non-null    float64
dtypes: float64(3), object(2)
memory usage: 35.9 KB